# Plugin provided by ProjectG

EnableAdminTools: true

# Item on join settings
ItemJoin: true
Slot: 4
DisableItemDrop: true
DisableItemMove: true

# Forms settings
Forms:
# Enable Player Button
  EnablePlayerForm: true
# Enable Mobs certain in form buttons
  EnableBossMobs: true
  EnableAggressiveMobs: true
  EnablePassiveMobs: true
# Enable Server button or certain in form buttons
  EnableServerForm: true
    EnableShutdown: false