# Plugin provided by ProjectG

EnableAdminTools: true

# Item on join settings
ItemJoin: true
Slot: 4
DisableItemDrop: true
DisableItemMove: true

# Forms settings
Forms:
  EnableAdminForm: true
  EnableModForm: true
  EnableMobForm: true
  EnableServerForm: true