# Plugin provided by ProjectG
# Do not change version value!
version: 1

# Available Languages en, nl
Language: en

EnableAdminTools: true

# Item on join settings
ItemJoin: true

###################
# Forms settings  #
###################

Forms:
  EnableAdminForm: true
  EnableModForm: true
  EnableCustomCommands: true
  EnableMobForm: true
  EnableServerForm: true

#####################
# Database config   #
#####################

EnableMySQL: false

host: localhost
port: 3306
database: GeyserAdminTools
username: root
password: password

######################
# Edit custom Form   #
######################

CommandsForm:
  # Set button text in main menu.
  ButtonMainMenu: Custom Commands
  # Set title and content text
  Title: Choose title
  Content: choose content

  # Button"1" = Button Name, SetCommand"1" = set command to button
  Button1: test1
  SetCommand1: "spawn"

  Button2: test2
  SetCommand2: "back"

  Button3: test3
  SetCommand3: "home"

  Button4: test4
  SetCommand4: ""

  Button5: test5
  SetCommand5: ""

  Button6: test6
  SetCommand6: ""

  Button7: test7
  SetCommand7: ""

  Button8: test8
  SetCommand8: ""

  Button9: test9
  SetCommand9: ""

  Button10: test10
  SetCommand10: ""

