name: GAdminTools
main: com.alysaa.geyseradmintools.Gat
version: 1.0
api-version: 1.15
description: Geyser Plugin Addon.
author: ProjectG
commands:
  gadmin:
    description: open admin panel
    permission: geyseradmintools.gadmin
    aliases: /gadmin
permissions:
  geyseradmintools.admintool:
    description: Allows to open admin form
    default: op
  geyseradmintools.modtool:
    description: Allows to open mod form
    default: op
  geyseradmintools.mobtool:
    description: Allows to open mob form
    default: op
  geyseradmintools.servertool:
    description: Allows to open server form
    default: op
  geyseradmintools.item:
    description: gives player admin item on join
    default: op
  geyseradmintools.customcommands:
    description: Allows to open Custom Commands form
    default: op
  geyseradmintools.banplayer:
    description: Allows to open ban form
    default: op

