name: GeyserAdminTools
main: com.alysaa.geyseradmintools.Gat
version: 1.1.0
api-version: 1.15
description: Geyser Plugin Addon.
author: ProjectG
depend: [floodgate]
commands:
  gadmin:
    description: open admin panel
    permission: geyseradmintools.gadmin
    aliases: /gadmin
  gban:
    description: ban player command for java
    permission: geyseradmintools.gban
    aliases: /gban
  gunban:
    description: unban player command for java
    permission: geyseradmintools.gunban
    aliases: /gunban
  gmute:
    description: mute player command for java
    permission: geyseradmintools.gmute
    aliases: /gmute
  gunmute:
    description: unmute player command for java
    permission: geyseradmintools.gunmute
    aliases: /gunmute
  greport:
    description: report command for java and bedrock
    permission: geyseradmintools.greport
    aliases: /greport
  gviewreport:
    description: report command for java and bedrock
    permission: geyseradmintools.gviewreport
    aliases: /gviewreport
permissions:
  geyseradmintools.admintool:
    description: Allows to open admin form
    default: op
  geyseradmintools.modtool:
    description: Allows to open mod form
    default: op
  geyseradmintools.mobtool:
    description: Allows to open mob form
    default: op
  geyseradmintools.servertool:
    description: Allows to open server form
    default: op
  geyseradmintools.item:
    description: gives player admin item on join
    default: op
  geyseradmintools.customcommands:
    description: Allows to open Custom Commands form
    default: op
  geyseradmintools.banplayer:
    description: Allows to open ban form
    default: op
  geyseradmintools.muteplayer:
    description: Allows to open mute form
    default: op
  geyseradmintools.viewreportplayer:
    description: Allows to use view button
    default: op
  geyseradmintools.reportplayer:
    description: Allows to use view button
    default: op