name: GeyserAdminTools
main: com.projectg.geyseradmintools.Gat
version: 1.2.0
api-version: 1.15
description: Geyser Plugin Addon.
author: ProjectG
depend: [floodgate]
commands:
  gadmin:
    description: Gives the player AdminTool item
    permission: geyseradmintools.gadmin
    aliases: /gadmin
  gban:
    description: ban player command for java
    permission: geyseradmintools.banplayer
    aliases: /gban
  gunban:
    description: unban player command for java
    permission: geyseradmintools.gunban
    aliases: /gunban
  gmute:
    description: mute player command for java
    permission: geyseradmintools.muteplayer
    aliases: /gmute
  gunmute:
    description: unmute player command for java
    permission: geyseradmintools.gunmute
    aliases: /gunmute
  greport:
    description: report command for java and bedrock
    permission: geyseradmintools.reportplayer
    aliases: /greport
  gviewreport:
    description: View report gui with tickets
    permission: geyseradmintools.viewreports
    aliases: /gviewreport
  gviewbans:
    description: View ban gui with playerheads
    permission: geyseradmintools.viewbans
    aliases: /gviewban
permissions:
  geyseradmintools.admintool:
    description: Allows to open admin form
    default: op
  geyseradmintools.modtool:
    description: Allows to open mod form
    default: op
  geyseradmintools.mobtool:
    description: Allows to open mob form
    default: op
  geyseradmintools.servertool:
    description: Allows to open server form
    default: op
  geyseradmintools.item:
    description: gives player admin item on join
    default: op
  geyseradmintools.customcommands:
    description: Allows to open Custom Commands form
    default: op
  geyseradmintools.banplayer:
    description: Allows to open ban form & use gban command
    default: op
  geyseradmintools.muteplayer:
    description: Allows to open mute form & use gmute command
    default: op
  geyseradmintools.reportplayer:
    description: Allows to use report player java command & report form
    default: op
  geyseradmintools.viewreports:
    description: Allows to use view button/ticket gui
    default: op
  geyseradmintools.viewbans:
    description: Allows to use view bans gui
    default: op
